/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FixedSizeList: typeof import('virtual-scroll-list-liudingkang/es/packages/fixed-size-list')['default']
  }
}
